### ISSUE TITLE
Permissions feel a bit broad?

### ISSUE THREAD

**Issue by M-Zuber** [hzuber/asana-task-manager#1]
I don't really know much about the permissions model, but is it possible to lower the default site access to just asana sites?

**Comment by hzuber** [comment]
The issue I found with that is that someone may want to view their tasks
while on a different site, and if permissions are restricted to asana
sites, that becomes impossible.

**Comment by M-Zuber** [comment]
Oh, I totally missed that it works on other sites 😄

**Comment by hzuber** [comment]
Lol, yeah :)
